[build]
  base = "/"
  command = "yarn install && yarn build"
  functions = ".netlify/functions"

[dev]
  command = "react-scripts start"
  functionsPort = 3002
  port = 3001

#[[redirects]]
#  from = "/api/*"
#  to = "/.netlify/functions/:splat"
#  status = 200